package practica3;

import java.awt.Color;

/**
 *
 * @author Javier Aranda Izquierdo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPractica3 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jButtonPractica3.setText("Boton");
        jButtonPractica3.addMouseListener(formListener);
        getContentPane().add(jButtonPractica3);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.MouseListener {
        FormListener() {}
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jButtonPractica3) {
                VentanaPrincipal.this.jButtonPractica3MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jButtonPractica3) {
                VentanaPrincipal.this.jButtonPractica3MouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jButtonPractica3) {
                VentanaPrincipal.this.jButtonPractica3MouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPractica3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPractica3MouseClicked
        // Evento de clicar que cambiar el color del boton
        this.jButtonPractica3.setBackground(Color.red);
    }//GEN-LAST:event_jButtonPractica3MouseClicked

    private void jButtonPractica3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPractica3MouseEntered
        // Evento al entrar en la region del boton cambia su fondo a color azul
        this.jButtonPractica3.setBackground(Color.blue);
    }//GEN-LAST:event_jButtonPractica3MouseEntered

    private void jButtonPractica3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPractica3MouseExited
        // Evento al salir de la zona del boton cambia su fonde a color verde
        this.jButtonPractica3.setBackground(Color.green);
    }//GEN-LAST:event_jButtonPractica3MouseExited



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPractica3;
    // End of variables declaration//GEN-END:variables
}
