/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.JAI.iu;

import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.Stroke;
import java.util.ArrayList;
import java.util.List;
import javafx.scene.paint.Color;
import static javafx.scene.paint.Color.color;

/**
 *
 * @author JaviAir
 */
public class Lienzo2D extends javax.swing.JPanel {

    /**
     * Creates new form Lienzo2D
     */
    public Lienzo2D() {
        initComponents();
    }

    private Color color=Color.BLACK;
    private static Stroke stroke = new BasicStroke((float)1.0);
    private final boolean relleno=false;
    private static boolean editar=false;
    private Shape s;
    static String forma;
    
    List<Shape> vShape = new ArrayList();
    
    public void paint(Graphics g){
                      super.paint(g);
                      Graphics2D g2d = (Graphics2D)g;
                      //g2d.setPaint(color);
                      //g2d.setStroke(stroke);
                      //g2d.setComposite(); y otra mas
                      for(Shape s:vShape) {
                        if(relleno) g2d.fill(s);
                        g2d.draw(s);
                      }
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public static Stroke getStroke() {
        return stroke;
    }

    public static void setStroke(Stroke stroke) {
        Lienzo2D.stroke = stroke;
    }

    public static boolean isEditar() {
        return editar;
    }

    public static void setEditar(boolean editar) {
        Lienzo2D.editar = editar;
    }

    public Shape getS() {
        return s;
    }

    public void setS(Shape s) {
        this.s = s;
    }

    public static String getForma() {
        return forma;
    }

    public static void setForma(String forma) {
        Lienzo2D.forma = forma;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
