package sm.JAI.iu;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Composite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Stroke;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author JaviAir
 */
public class Lienzo2D extends javax.swing.JPanel {

    /**
     * Creates new form Lienzo2D
     */
    public Lienzo2D() {
        initComponents();
    }
    
    // Declaracion de variables generales
    private static Color color=Color.BLACK;
    private static Stroke stroke = new BasicStroke((float)1.0);
    private static Composite composicion;
    private static RenderingHints render;
    private final boolean relleno=false;
    private static boolean editar=false;
    private Shape s;
    static String forma;
    
    List<Shape> vShape = new ArrayList();
    
    // Implementacion del metodo paint
    public void paint(Graphics g){
                      super.paint(g);
                      Graphics2D g2d = (Graphics2D)g;
                      g2d.setPaint(color);
                      g2d.setStroke(stroke);
                      g2d.setComposite(composicion); 
                      g2d.setRenderingHints(render);
                      for(Shape s:vShape) {
                        if(relleno) g2d.fill(s);
                        g2d.draw(s);
                      }
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public static Stroke getStroke() {
        return stroke;
    }

    public static void setStroke(Stroke stroke) {
        Lienzo2D.stroke = stroke;
    }

    public static boolean isEditar() {
        return editar;
    }

    public static void setEditar(boolean editar) {
        Lienzo2D.editar = editar;
    }

    public Shape getS() {
        return s;
    }

    public void setS(Shape s) {
        this.s = s;
    }

    public static String getForma() {
        return forma;
    }

    public static void setForma(String forma) {
        Lienzo2D.forma = forma;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // Codigo para el MousePressed
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // Codigo para el MouseReleased
    }//GEN-LAST:event_formMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // Codigo para el MouseDragged
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
