package practica4;

import java.awt.Color;
import static java.awt.Color.black;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author Javier Aranda Izquiedo
 */
public class Lienzo extends javax.swing.JPanel {

    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        this.c = black;
        initComponents();
    }
    
    Point p; //Punto para dibujar solo puntos
    Point pInicial;  //Punto inical
    Point pFinal;  //Punto final
    private Color c; 
    boolean relleno=false; //Variable para el relleno
    //static final String forma;
    String forma;
    
    public Color getColor() {
        return c;
    }

    public void setColor(Color c) {
        this.c = c;
    }

    public boolean isRelleno() {
        return relleno;
    }

    public void setRelleno(boolean relleno) {
        this.relleno = relleno;
    }

    
    
    @Override
    public void paint(Graphics g){
        super.paint (g);
        
        // Código (mensajes a g)
        g.setColor(c);
        
        if(p!=null){
            
            /*switch(forma){
                case "punto":
                    g.fillOval(p.x, p.y, 10, 10);
                    
            }*/
           
                    
        g.fillOval(p.x, p.y, 10, 10);}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // Cuando haces click en el Lienzo
        p=evt.getPoint();
        this.repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
