package practica4;

/**
 *
 * @author Javier Aranda
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHerramientasDibujo = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButtonPunto = new javax.swing.JToggleButton();
        jToggleButtonLinea = new javax.swing.JToggleButton();
        jToggleButtonRectangulo = new javax.swing.JToggleButton();
        jToggleButtonOvalo = new javax.swing.JToggleButton();
        jTextFieldBarraInferior = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButtonColorNegro = new javax.swing.JToggleButton();
        jToggleButtonColorRojo = new javax.swing.JToggleButton();
        jToggleButtonColorAzul = new javax.swing.JToggleButton();
        jToggleButtonColorBlanco = new javax.swing.JToggleButton();
        jToggleButtonColorAmarillo = new javax.swing.JToggleButton();
        jToggleButtonColorVerde = new javax.swing.JToggleButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemAbrirç = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuEdicion = new javax.swing.JMenu();
        jCheckBoxMenuItemEdicion = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        buttonGroupHerramientasDibujo.add(jToggleButtonPunto);
        jToggleButtonPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lapiz.gif"))); // NOI18N
        jToggleButtonPunto.setFocusable(false);
        jToggleButtonPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonPunto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonPunto);

        buttonGroupHerramientasDibujo.add(jToggleButtonLinea);
        jToggleButtonLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Linea.gif"))); // NOI18N
        jToggleButtonLinea.setFocusable(false);
        jToggleButtonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonLinea);

        buttonGroupHerramientasDibujo.add(jToggleButtonRectangulo);
        jToggleButtonRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Rectangulo.gif"))); // NOI18N
        jToggleButtonRectangulo.setFocusable(false);
        jToggleButtonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonRectangulo);

        buttonGroupHerramientasDibujo.add(jToggleButtonOvalo);
        jToggleButtonOvalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ovalo.gif"))); // NOI18N
        jToggleButtonOvalo.setFocusable(false);
        jToggleButtonOvalo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonOvalo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jToggleButtonOvalo);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jTextFieldBarraInferior, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToggleButtonColorNegro.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jToggleButtonColorNegro);

        jToggleButtonColorRojo.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jToggleButtonColorRojo);

        jToggleButtonColorAzul.setBackground(new java.awt.Color(0, 0, 153));
        jPanel2.add(jToggleButtonColorAzul);

        jToggleButtonColorBlanco.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jToggleButtonColorBlanco);

        jToggleButtonColorAmarillo.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.add(jToggleButtonColorAmarillo);

        jToggleButtonColorVerde.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.add(jToggleButtonColorVerde);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuArchivo.setText("Archivo");

        jMenuItemNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemNuevo.setText("Nuevo");
        jMenuArchivo.add(jMenuItemNuevo);

        jMenuItemAbrirç.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemAbrirç.setText("Abrir");
        jMenuArchivo.add(jMenuItemAbrirç);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemGuardar.setText("Guardar");
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuBar2.add(jMenuArchivo);

        jMenuEdicion.setText("Edición");

        jCheckBoxMenuItemEdicion.setSelected(true);
        jCheckBoxMenuItemEdicion.setText("Ver barra de estado");
        jCheckBoxMenuItemEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemEdicionActionPerformed(evt);
            }
        });
        jMenuEdicion.add(jCheckBoxMenuItemEdicion);

        jMenuBar2.add(jMenuEdicion);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItemEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemEdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItemEdicionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupHerramientasDibujo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEdicion;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuEdicion;
    private javax.swing.JMenuItem jMenuItemAbrirç;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldBarraInferior;
    private javax.swing.JToggleButton jToggleButtonColorAmarillo;
    private javax.swing.JToggleButton jToggleButtonColorAzul;
    private javax.swing.JToggleButton jToggleButtonColorBlanco;
    private javax.swing.JToggleButton jToggleButtonColorNegro;
    private javax.swing.JToggleButton jToggleButtonColorRojo;
    private javax.swing.JToggleButton jToggleButtonColorVerde;
    private javax.swing.JToggleButton jToggleButtonLinea;
    private javax.swing.JToggleButton jToggleButtonOvalo;
    private javax.swing.JToggleButton jToggleButtonPunto;
    private javax.swing.JToggleButton jToggleButtonRectangulo;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
