/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica6;

import java.awt.Composite;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Stroke;
import java.awt.geom.AffineTransform;

/**
 *
 * @author JaviAir
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void paint(Graphics g){
           super.paint(g);
           Graphics2D g2d = (Graphics2D)g;
           this.setAtributos(g2d);
        Iterable<Shape> vShape = null;
           for(Shape s:vShape) g2d.draw(s);
}
         private void setAtributos(Graphics2D g2d){
           
            //Trazo
            Stroke trazo=null;
            // TODO: Código para crear trazo
            g2d.setStroke(trazo);
            
            //Relleno
            Paint relleno=null;
            // TODO: Código para crear relleno
            g2d.setPaint(relleno);
           
            //Composición
            Composite composicion = null;
            // TODO: Código para crear composición
            g2d.setComposite(composicion);
           
            //Transformación
            AffineTransform transformacion = null;
            // TODO: Código para crear transformación
            g2d.setTransform(transformacion);
            
            //Fuente
            Font fuente = null;
            // TODO: Código para crear fuente
            g2d.setFont(fuente);
           
            //Renderización
            RenderingHints render = null;
            // TODO: Código para crear renderizado
            g2d.setRenderingHints(render);
           
            //Recorte
            Shape clip = null;
            // TODO: Código para crear clip
            g2d.setClip(clip);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
