package Final;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;


/**
 *
 * @author Javier Aranda
 */
public class VentanaInternaReproductor extends javax.swing.JInternalFrame {

    SMClipPlayer player;
    
    public VentanaInternaReproductor(File f) {
       
        initComponents();
        player=new SMClipPlayer(f);
        player.setLineListener(escuchador);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BotonPlay = new javax.swing.JToggleButton();
        BotonStop = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);

        buttonGroup1.add(BotonPlay);
        BotonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PlayDisabled_48x48.png"))); // NOI18N
        BotonPlay.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PlayPressed_48x48.png"))); // NOI18N
        BotonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPlayActionPerformed(evt);
            }
        });

        buttonGroup1.add(BotonStop);
        BotonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StopDisabled_48x48.png"))); // NOI18N
        BotonStop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/StopPessedBlue_48x48.png"))); // NOI18N
        BotonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonStop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPlayActionPerformed
        // Reproducir audio
        if(player!=null)player.play();
    }//GEN-LAST:event_BotonPlayActionPerformed

    private void BotonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonStopActionPerformed
        // Parar el audio
        if(player!=null)player.stop();
    }//GEN-LAST:event_BotonStopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonPlay;
    private javax.swing.JToggleButton BotonStop;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables

    LineListener escuchador = new LineListener(){
        @Override
        public void update(LineEvent le) {
            if(le.getType()==LineEvent.Type.STOP){
                buttonGroup1.clearSelection();
            } 
        }
    };

}
